# Generated by Django 3.1.5 on 2021-02-21 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(default='', max_length=30, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='identifier',
            field=models.CharField(default='', max_length=15, verbose_name='Идентификатор'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telephone',
            field=models.CharField(default='', max_length=13, verbose_name='Телефон'),
        ),
    ]
