# Generated by Django 3.1.5 on 2021-02-21 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210221_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='identifier',
            field=models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telephone',
            field=models.CharField(blank=True, default='', max_length=13, null=True, verbose_name='Телефон'),
        ),
    ]
