# Generated by Django 3.1.5 on 2021-03-22 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='communiti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ava', imagekit.models.fields.ProcessedImageField(blank=True, default='communitiimages/def.png', upload_to='communitiimages/', verbose_name='Изображение')),
                ('title', models.CharField(default=' ', max_length=100, verbose_name='Название')),
                ('Description', models.CharField(default=' ', max_length=200, verbose_name='Описание')),
                ('subscribers', models.IntegerField(default=0, verbose_name='Подписчики')),
                ('rating', models.IntegerField(default=0, verbose_name='Рейтинг')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=80, verbose_name='Название')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('communiti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communities.communiti')),
            ],
        ),
        migrations.CreateModel(
            name='tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('communiti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communities.communiti')),
            ],
        ),
    ]
