# Generated by Django 3.1.5 on 2021-03-31 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_communiti_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='communiti',
            name='identifier',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Идентификатор'),
        ),
    ]
