# Generated by Django 3.1.5 on 2021-02-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20210228_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='DateCreate',
            field=models.DateTimeField(auto_now_add=True,verbose_name='Дата публикации'),
            preserve_default=False,
        ),
    ]
