# Generated by Django 3.1.5 on 2021-02-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_datecreate'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cover',
            field=models.TextField(default=' ', verbose_name='Обложка'),
        ),
    ]
