# Generated by Django 3.1.5 on 2021-03-06 09:07

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20210305_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='Контент'),
        ),
    ]
