# Generated by Django 3.1.5 on 2021-03-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_views_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='deleted',
            field=models.BooleanField(default=0, verbose_name='Удалено'),
        ),
        migrations.AddField(
            model_name='article',
            name='hidden',
            field=models.BooleanField(default=0, verbose_name='Скрыто'),
        ),
        migrations.AddField(
            model_name='article',
            name='limited',
            field=models.BooleanField(default=0, verbose_name='Ограничено'),
        ),
    ]
