# Generated by Django 3.1.2 on 2021-03-27 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_auto_20210321_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='tag_base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='тег')),
            ],
        ),
        migrations.AlterField(
            model_name='articles_tag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.tag_base'),
        ),
    ]
