# Generated by Django 3.1.2 on 2021-03-27 09:43

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_auto_20210327_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag_base',
            name='description',
            field=models.CharField(default=' ', max_length=200, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='tag_base',
            name='img',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='tagimages/def.png', upload_to='tagimages/', verbose_name='Изображение'),
        ),
    ]
