# Generated by Django 3.1.5 on 2021-02-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='beginner',
            field=models.BooleanField(default=True),
        ),
    ]
