# Generated by Django 3.1.5 on 2021-02-23 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_beginner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Points',
            field=models.IntegerField(default=0, verbose_name='Баллы'),
        ),
        migrations.AddField(
            model_name='user',
            name='messages_count',
            field=models.IntegerField(default=0, verbose_name='Кол-во сообщений'),
        ),
    ]
