# Generated by Django 3.1.5 on 2021-02-26 13:00

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210226_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='userimages/def.png', upload_to='userimages/', verbose_name='Изображение'),
        ),
    ]
