# Generated by Django 3.1.5 on 2021-02-28 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_tag_interest_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag_interest_user',
            old_name='tag',
            new_name='tag_user',
        ),
    ]
