# Generated by Django 3.1.2 on 2021-03-05 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20210303_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag_interest_user',
            name='tag_id',
            field=models.IntegerField(default=-1),
        ),
    ]
