# Generated by Django 3.1.2 on 2021-03-27 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_auto_20210327_1443'),
        ('accounts', '0010_tag_interest_user_tag_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag_interest_user',
            name='tag_id',
        ),
        migrations.RemoveField(
            model_name='tag_interest_user',
            name='tag_user',
        ),
        migrations.AddField(
            model_name='tag_interest_user',
            name='tag',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='articles.tag_base'),
            preserve_default=False,
        ),
    ]
