# Generated by Django 3.1.5 on 2021-03-31 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20210327_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Description',
            field=models.CharField(default=' ', max_length=200, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='user',
            name='subscribers',
            field=models.IntegerField(default=0, verbose_name='Подписчики'),
        ),
    ]
