# Generated by Django 3.1.5 on 2021-04-02 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20210331_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_inter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_i', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
