# Generated by Django 3.1.5 on 2021-03-22 06:03

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название статьи')),
                ('text_mini', models.TextField(default=' ', verbose_name='Краткий текст статьи')),
                ('text', tinymce.models.HTMLField(verbose_name='Контент')),
                ('views', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('likes', models.IntegerField(default=0, verbose_name='Лайки')),
                ('dilikes', models.IntegerField(default=0, verbose_name='Дизлайки')),
                ('DateCreate', models.DateTimeField(blank=True, default='2000.10.10', verbose_name='Дата публикации')),
                ('communiti', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='communities.communiti')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
