# Generated by Django 3.1.5 on 2021-03-22 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
        ('news', '0002_auto_20210322_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='communiti',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communities.communiti'),
        ),
    ]
