# Generated by Django 3.1.5 on 2021-03-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20210322_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='new_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images_news/')),
            ],
        ),
    ]
