# Generated by Django 3.1.2 on 2021-02-01 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='text',
            field=models.TextField(verbose_name='Текст статьи'),
        ),
    ]
