# Generated by Django 3.1.2 on 2021-02-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210202_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='new_img',
            field=models.ImageField(default='1', upload_to='newimage/', verbose_name='Картинка новости 1200x552'),
        ),
    ]
