# Generated by Django 3.1.5 on 2021-02-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_new_new_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='new',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AddField(
            model_name='new',
            name='text_mini',
            field=models.TextField(default='1', verbose_name='Краткий текст статьи'),
        ),
    ]
